#!/usr/bin/env python3
# Generates sw/test5.c : a big INT8 MLP (64 -> 64 -> 32 -> 16) whose constant
# weight tables (6656 B of .rodata) cannot fit the old 4K SRAM but do fit the
# 16K SRAM. Weights + the golden output vector are produced here with the EXACT
# integer arithmetic the device performs, so the on-target run is self-checking.
#
# Run:  python3 sw/gen_test5.py  > sw/test5.c   (or it writes the file directly)

IN, H1, H2, OUT = 64, 64, 32, 16
SHIFT1, SHIFT2, SHIFT3 = 2, 6, 5

# --- deterministic LCG (glibc constants), same stream the C file documents ----
class LCG:
    def __init__(self, seed): self.s = seed & 0x7fffffff
    def next(self):
        self.s = (1103515245 * self.s + 12345) & 0x7fffffff
        return self.s

rng = LCG(0xC0DE1234)

def small_signed():            # weights in [-1, 3] (mean +1 -> signal propagates)
    return (rng.next() % 5) - 1
def small_input():             # activations in [0, 7]
    return rng.next() % 8

w1 = [small_signed() for _ in range(H1 * IN)]
w2 = [small_signed() for _ in range(H2 * H1)]
w3 = [small_signed() for _ in range(OUT * H2)]
x  = [small_input()  for _ in range(IN)]

# --- exact device arithmetic (int32 accumulate, arithmetic >>, clamp) ---------
def relu_requant(acc, s):
    if acc < 0: acc = 0
    acc >>= s
    if acc > 127: acc = 127
    return acc                  # 0..127, fits int8
def sat_requant(acc, s):
    acc >>= s                   # arithmetic shift (Python floor == GCC signed)
    if acc >  127: acc =  127
    if acc < -128: acc = -128
    return acc

def forward():
    h1 = [relu_requant(sum(w1[o*IN+i]*x[i]  for i in range(IN)),  SHIFT1) for o in range(H1)]
    h2 = [relu_requant(sum(w2[o*H1+i]*h1[i] for i in range(H1)), SHIFT2) for o in range(H2)]
    y  = [sat_requant (sum(w3[o*H2+i]*h2[i] for i in range(H2)), SHIFT3) for o in range(OUT)]
    return h1, h2, y

h1, h2, y = forward()

# --- emit C ------------------------------------------------------------------
def arr(name, vals, perline=16):
    lines = []
    for i in range(0, len(vals), perline):
        lines.append("    " + ", ".join("%4d" % v for v in vals[i:i+perline]) + ",")
    return "static const int8_t %s[%d] = {\n%s\n};\n" % (name, len(vals), "\n".join(lines))

C = f'''// Copyright (c) 2026 ETH Zurich.
// Licensed under Solderpad Hardware License 0.51.
//
// test5.c — GENERATED by gen_test5.py.  Big INT8 MLP {IN}->{H1}->{H2}->{OUT}.
//
// PURPOSE: stress the SRAM-size bump (512 -> 2048 words/bank = 16 KB). The three
// weight tables below are {H1*IN}+{H2*H1}+{OUT*H2} = {H1*IN+H2*H1+OUT*H2} bytes of .rodata. With code +
// stack the image is several KB -> it does NOT fit the old 4K SRAM (the link.ld
// ASSERT fires) but DOES fit 16K, and a correct run proves the upper banks
// (above the old 0x1000_0800 boundary) are actually reachable.
//
// Pure software (no MAC HWPE): this isolates the memory change. Runs on the
// current main (RV32MNone -> emulated multiply; slow but correct). Self-checking
// against a golden vector computed by gen_test5.py with identical int arithmetic.
//
// Expected: y == GOLDEN (printed), PASS.

#include <stdint.h>
#include "uart.h"

static inline uint32_t read_mcycle(void) {{
#ifdef __riscv
    uint32_t v; asm volatile("csrr %0, mcycle" : "=r"(v)); return v;
#else
    return 0;  // host self-check build: no cycle counter
#endif
}}
static void print_str(const char *s) {{ while (*s) uart_write((uint8_t)*s++); }}
static void print_int(int32_t v) {{
    if (v < 0) {{ uart_write('-'); v = -v; }}
    if (v == 0) {{ uart_write('0'); return; }}
    char buf[12]; int n = 0;
    while (v > 0) {{ buf[n++] = (char)('0' + (v % 10)); v /= 10; }}
    while (n--) uart_write((uint8_t)buf[n]);
}}
static void print_vec(const char *label, const int8_t *v, int n) {{
    print_str(label); uart_write('[');
    for (int i = 0; i < n; i++) {{ if (i) uart_write(','); print_int(v[i]); }}
    uart_write(']'); uart_write('\\n');
}}

#define IN   {IN}
#define H1   {H1}
#define H2   {H2}
#define OUT  {OUT}
#define SHIFT1 {SHIFT1}
#define SHIFT2 {SHIFT2}
#define SHIFT3 {SHIFT3}

{arr("w1", w1)}
{arr("w2", w2)}
{arr("w3", w3)}
{arr("x_test", x)}
{arr("GOLDEN", y)}

static int8_t relu_requant(int32_t acc, int s) {{
    if (acc < 0) acc = 0;
    acc >>= s;
    if (acc > 127) acc = 127;
    return (int8_t)acc;
}}
static int8_t sat_requant(int32_t acc, int s) {{
    acc >>= s;
    if (acc >  127) acc =  127;
    if (acc < -128) acc = -128;
    return (int8_t)acc;
}}

// scratch buffers live in .bss (more SRAM exercise)
static int8_t h1[H1], h2[H2], y_out[OUT];

static void mlp_sw(void) {{
    for (int o = 0; o < H1; ++o) {{
        int32_t acc = 0;
        for (int i = 0; i < IN; ++i) acc += (int32_t)w1[o*IN+i] * (int32_t)x_test[i];
        h1[o] = relu_requant(acc, SHIFT1);
    }}
    for (int o = 0; o < H2; ++o) {{
        int32_t acc = 0;
        for (int i = 0; i < H1; ++i) acc += (int32_t)w2[o*H1+i] * (int32_t)h1[i];
        h2[o] = relu_requant(acc, SHIFT2);
    }}
    for (int o = 0; o < OUT; ++o) {{
        int32_t acc = 0;
        for (int i = 0; i < H2; ++i) acc += (int32_t)w3[o*H2+i] * (int32_t)h2[i];
        y_out[o] = sat_requant(acc, SHIFT3);
    }}
}}

// --- HW path: original scalar mac_unit.sv (acc += A*B, one store per term) ---
// Register map (user base 0x2000_0000): 0x00 MAC[W]{{B,A}}, 0x04 CLEAR[W],
// 0x08 RESULT[R]. ReLU/requantize stay in SW. Device-only.
#ifdef __riscv
#define MAC_BASE_ADDR (0x20000000UL)
#define MAC_DO     (*((volatile uint32_t *)(MAC_BASE_ADDR + 0x00)))
#define MAC_CLEAR  (*((volatile uint32_t *)(MAC_BASE_ADDR + 0x04)))
#define MAC_RESULT (*((volatile int32_t  *)(MAC_BASE_ADDR + 0x08)))
static inline void    mac_clear(void)            {{ MAC_CLEAR = 0; }}
static inline void    mac_acc(int8_t a, int8_t b){{ MAC_DO = (uint32_t)(uint8_t)a | ((uint32_t)(uint8_t)b << 8); }}
static inline int32_t mac_result(void)           {{ return (int32_t)MAC_RESULT; }}

static int8_t h1_hw[H1], h2_hw[H2], y_hw[OUT];

static void mlp_hw(void) {{
    for (int o = 0; o < H1; ++o) {{
        mac_clear();
        for (int i = 0; i < IN; ++i) mac_acc(w1[o*IN+i], x_test[i]);
        h1_hw[o] = relu_requant(mac_result(), SHIFT1);
    }}
    for (int o = 0; o < H2; ++o) {{
        mac_clear();
        for (int i = 0; i < H1; ++i) mac_acc(w2[o*H1+i], h1_hw[i]);
        h2_hw[o] = relu_requant(mac_result(), SHIFT2);
    }}
    for (int o = 0; o < OUT; ++o) {{
        mac_clear();
        for (int i = 0; i < H2; ++i) mac_acc(w3[o*H2+i], h2_hw[i]);
        y_hw[o] = sat_requant(mac_result(), SHIFT3);
    }}
}}
#endif

int main(void) {{
    uart_init();

    uint32_t t0 = read_mcycle();
    mlp_sw();
    uint32_t cyc_sw = read_mcycle() - t0;

    print_vec("SW y=",   y_out,  OUT);
    print_vec("golden=", GOLDEN, OUT);
    print_str("SW cyc="); print_int((int32_t)cyc_sw); uart_write('\\n');

    int pass = 1;
    for (int i = 0; i < OUT; ++i) if (y_out[i] != GOLDEN[i]) pass = 0;

#ifdef __riscv
    uint32_t t1 = read_mcycle();
    mlp_hw();
    uint32_t cyc_hw = read_mcycle() - t1;

    print_vec("HW y=", y_hw, OUT);
    print_str("HW cyc="); print_int((int32_t)cyc_hw); uart_write('\\n');
    for (int i = 0; i < OUT; ++i) if (y_hw[i] != GOLDEN[i]) pass = 0;

    if (cyc_hw < cyc_sw) {{ print_str("MAC faster by "); print_int((int32_t)(cyc_sw - cyc_hw)); }}
    else                 {{ print_str("Core faster by "); print_int((int32_t)(cyc_hw - cyc_sw)); }}
    print_str(" cyc\\n");
#endif

    print_str(pass ? "PASS\\n" : "FAIL\\n");

    uart_write_flush();
    return pass ? 0 : 1;
}}
'''

import os
out = os.path.join(os.path.dirname(__file__), "test5.c")
with open(out, "w") as f:
    f.write(C)
print("wrote", out)
print("golden y =", y)
print("h1[:8] =", h1[:8], "  h2[:8] =", h2[:8])
print("rodata weights =", H1*IN + H2*H1 + OUT*H2, "bytes")
